import os
import json
import subprocess
import ssl
import pwd
import ldap3
import time
import saml2
from ldap3 import Server, Connection, Tls
from flask import Flask, redirect, url_for, session, render_template_string, abort, request, send_from_directory

app = Flask(__name__)
app.secret_key = os.getenv('FLASK_SECRET_KEY', 'change-me-in-prod')

# Load SAML config generated by generate_saml_config.py
SAML_CONFIG_PATH = '/etc/kasm/auth/saml_google.json'
if os.path.exists(SAML_CONFIG_PATH):
    with open(SAML_CONFIG_PATH) as f:
        saml_cfg = json.load(f)
else:
    saml_cfg = {}
LOGIN_PAGE = """<!doctype html>
<html lang='en'>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Remote Desktop - Sign In</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap" rel="stylesheet">
    <style>
      :root {
        --primary: #EF4C17;
        --primary-hover: #ff6836;
        --bg-gradient: linear-gradient(135deg, #000000 0%, #1c0903 100%);
        --panel-bg: rgba(15, 15, 15, 0.85);
        --text-main: #ffffff;
        --text-muted: #8a8a8a;
      }
      
      * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        font-family: 'Outfit', sans-serif;
      }
      
      body {
        background: var(--bg-gradient);
        color: var(--text-main);
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        position: relative;
      }

      .blob {
        position: absolute;
        width: 500px;
        height: 500px;
        background: radial-gradient(circle, rgba(239, 76, 23, 0.12) 0%, rgba(0,0,0,0) 70%);
        border-radius: 50%;
        z-index: 0;
        animation: float 20s infinite alternate;
      }
      .blob-1 {
        top: -10%;
        left: -10%;
      }
      .blob-2 {
        bottom: -10%;
        right: -10%;
        animation-delay: -10s;
      }

      @keyframes float {
        0% { transform: translate(0, 0) scale(1); }
        100% { transform: translate(50px, 50px) scale(1.1); }
      }

      .login-container {
        position: relative;
        z-index: 10;
        background: var(--panel-bg);
        backdrop-filter: blur(16px);
        -webkit-backdrop-filter: blur(16px);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 24px;
        padding: 3.5rem 3rem;
        width: 100%;
        max-width: 440px;
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);
        text-align: center;
        transform: translateY(0);
        transition: all 0.3s ease;
        animation: fadeIn 0.8s cubic-bezier(0.16, 1, 0.3, 1);
      }

      @keyframes fadeIn {
        from { opacity: 0; transform: translateY(20px); }
        to { opacity: 1; transform: translateY(0); }
      }

      .logo-icon {
        width: 64px;
        height: 64px;
        background: rgba(239, 76, 23, 0.05);
        border: 1px solid rgba(239, 76, 23, 0.25);
        border-radius: 16px;
        margin: 0 auto 1.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 8px 32px rgba(239, 76, 23, 0.15);
      }

      .logo-icon svg {
        width: 48px;
        height: 48px;
      }

      h1 {
        font-size: 2rem;
        font-weight: 800;
        margin-bottom: 0.5rem;
        letter-spacing: -0.5px;
        background: linear-gradient(to right, #ffffff, #cbd5e1);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
      }

      .subtitle {
        color: var(--text-muted);
        font-size: 0.95rem;
        margin-bottom: 2.5rem;
        font-weight: 300;
      }

      .form-group {
        margin-bottom: 1.5rem;
        text-align: left;
      }

      label {
        display: block;
        font-size: 0.85rem;
        font-weight: 600;
        margin-bottom: 0.5rem;
        color: var(--text-muted);
        text-transform: uppercase;
        letter-spacing: 0.5px;
      }

      input[type="text"], input[type="password"] {
        width: 100%;
        padding: 0.85rem 1rem;
        background: rgba(0, 0, 0, 0.6);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 12px;
        color: var(--text-main);
        font-size: 1rem;
        transition: all 0.2s;
        outline: none;
      }

      input[type="text"]:focus, input[type="password"]:focus {
        border-color: var(--primary);
        box-shadow: 0 0 0 3px rgba(239, 76, 23, 0.25);
        background: rgba(0, 0, 0, 0.8);
      }

      button {
        width: 100%;
        padding: 1rem;
        background: linear-gradient(135deg, var(--primary) 0%, #c43508 100%);
        border: none;
        border-radius: 12px;
        color: white;
        font-size: 1rem;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.2s ease;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 0.5rem;
        box-shadow: 0 4px 12px rgba(239, 76, 23, 0.2);
        margin-top: 1.5rem;
      }

      button:hover {
        transform: translateY(-1px);
        box-shadow: 0 6px 20px rgba(239, 76, 23, 0.35);
        background: linear-gradient(135deg, var(--primary-hover) 0%, #EF4C17 100%);
      }

      button:active {
        transform: translateY(0);
      }

      .footer-text {
        margin-top: 2rem;
        font-size: 0.8rem;
        color: var(--text-muted);
        font-weight: 300;
      }
    </style>
  </head>
  <body>
    <div class="blob blob-1"></div>
    <div class="blob blob-2"></div>
    
    <div class="login-container">
      <div class="logo-icon">
        <svg viewBox="0 0 100 100">
          <path d="M 50 15 C 62 25, 62 45, 50 50 C 38 45, 38 25, 50 15 Z" fill="#EF4C17" transform="rotate(0 50 50)"/>
          <path d="M 50 15 C 62 25, 62 45, 50 50 C 38 45, 38 25, 50 15 Z" fill="#EF4C17" transform="rotate(90 50 50)"/>
          <path d="M 50 15 C 62 25, 62 45, 50 50 C 38 45, 38 25, 50 15 Z" fill="#EF4C17" transform="rotate(180 50 50)"/>
          <path d="M 50 15 C 62 25, 62 45, 50 50 C 38 45, 38 25, 50 15 Z" fill="#EF4C17" transform="rotate(270 50 50)"/>
          <circle cx="50" cy="50" r="6" fill="#FFFFFF"/>
        </svg>
      </div>
      <h1>Persimmons Access</h1>
      <p class="subtitle">Secure login for Remote Desktop Environment</p>
      
      {% if error %}
      <div class="error-msg" style="color: #ef4444; background: rgba(239, 68, 68, 0.1); border: 1px solid rgba(239, 68, 68, 0.2); padding: 0.75rem; border-radius: 12px; margin-bottom: 1.5rem; font-size: 0.9rem; text-align: left;">
        {{ error }}
      </div>
      {% endif %}

      <p style="color: var(--text-muted); font-size: 0.95rem; margin-bottom: 2rem; font-weight: 300; line-height: 1.5;">
        Access to this system is restricted to authorized users. Please sign in using your corporate Google Workspace identity.
      </p>

      <a href="{{ url_for('saml_login') }}" style="display: flex; align-items: center; justify-content: center; gap: 0.75rem; width: 100%; padding: 1.1rem; background: linear-gradient(135deg, var(--primary) 0%, #c43508 100%); border: none; border-radius: 12px; color: white; text-decoration: none; font-size: 1.05rem; font-weight: 600; transition: all 0.2s ease; box-shadow: 0 4px 12px rgba(239, 76, 23, 0.2);" onmouseover="this.style.transform='translateY(-1px)'; this.style.boxShadow='0 6px 20px rgba(239, 76, 23, 0.35)';" onmouseout="this.style.transform='translateY(0)'; this.style.boxShadow='0 4px 12px rgba(239, 76, 23, 0.2)';">
        <svg style="width: 20px; height: 20px;" viewBox="0 0 24 24">
          <path fill="#FFFFFF" d="M23.745 12.27c0-.7-.06-1.4-.19-2.07H12v3.9h6.69c-.29 1.5-.1.85-2.07 3.2v2.66h3.3c1.92-1.77 3.02-4.38 3.02-7.69z"/>
          <path fill="#FFFFFF" d="M12 24c3.24 0 5.95-1.08 7.93-2.91l-3.3-2.66c-.92.62-2.11 1-3.63 1-3.14 0-5.8-2.11-6.75-4.96H2.9v2.74C4.88 20.31 8.19 24 12 24z"/>
          <path fill="#FFFFFF" d="M5.25 14.47c-.25-.75-.39-1.56-.39-2.47s.14-1.72.39-2.47V6.79H2.9C2.08 8.43 1.62 10.16 1.62 12s.46 3.57 1.28 5.21l2.35-2.74z"/>
          <path fill="#FFFFFF" d="M12 4.75c1.77 0 3.35.61 4.6 1.8l3.42-3.42C17.95 1.19 15.24 0 12 0 8.19 0 4.88 3.69 2.9 7.66l3.35 2.74c.95-2.85 3.61-4.96 6.75-4.96z"/>
        </svg>
        Sign In with Google SSO
      </a>
      
      <p class="footer-text" style="margin-top: 1.5rem;">Protected by Google SAML SSO</p>
    </div>
  </body>
</html>
"""
@app.route('/')
def index():
    if 'user' in session:
        # User already authenticated – redirect to noVNC URL
        return redirect(url_for('novnc', cb=int(time.time())))
    
    error = request.args.get('error')
    if error:
        return render_template_string(LOGIN_PAGE, error=error)
    return redirect(url_for('saml_login'))

@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

SHUTDOWN_PAGE = """
<!doctype html>
<html lang='en'>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Session Ended</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap" rel="stylesheet">
    <style>
      :root {
        --primary: #EF4C17;
        --bg-gradient: linear-gradient(135deg, #000000 0%, #1c0903 100%);
        --panel-bg: rgba(15, 15, 15, 0.85);
        --text-main: #ffffff;
        --text-muted: #8a8a8a;
      }
      
      * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        font-family: 'Outfit', sans-serif;
      }
      
      body {
        background: var(--bg-gradient);
        color: var(--text-main);
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        position: relative;
      }

      .container {
        position: relative;
        z-index: 10;
        background: var(--panel-bg);
        backdrop-filter: blur(16px);
        -webkit-backdrop-filter: blur(16px);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 24px;
        padding: 3.5rem 3rem;
        width: 100%;
        max-width: 440px;
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);
        text-align: center;
        animation: fadeIn 0.8s cubic-bezier(0.16, 1, 0.3, 1);
      }

      @keyframes fadeIn {
        from { opacity: 0; transform: translateY(20px); }
        to { opacity: 1; transform: translateY(0); }
      }

      .icon {
        width: 64px;
        height: 64px;
        background: rgba(239, 76, 23, 0.05);
        border: 1px solid rgba(239, 76, 23, 0.25);
        border-radius: 16px;
        margin: 0 auto 1.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 8px 32px rgba(239, 76, 23, 0.15);
      }

      h1 {
        font-size: 2rem;
        font-weight: 800;
        margin-bottom: 0.5rem;
        letter-spacing: -0.5px;
        background: linear-gradient(to right, #ffffff, #cbd5e1);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
      }

      .subtitle {
        color: var(--text-muted);
        font-size: 0.95rem;
        margin-bottom: 2rem;
        font-weight: 300;
        line-height: 1.5;
      }

      .btn {
        display: inline-block;
        width: 100%;
        padding: 1rem;
        background: linear-gradient(135deg, var(--primary) 0%, #c43508 100%);
        border: none;
        border-radius: 12px;
        color: white;
        text-decoration: none;
        font-size: 1rem;
        font-weight: 600;
        transition: all 0.2s ease;
        box-shadow: 0 4px 12px rgba(239, 76, 23, 0.2);
      }

      .btn:hover {
        transform: translateY(-1px);
        box-shadow: 0 6px 20px rgba(239, 76, 23, 0.35);
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="icon">
        <svg style="width: 32px; height: 32px;" viewBox="0 0 24 24">
          <path fill="#EF4C17" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9Z"/>
        </svg>
      </div>
      <h1>Session Ended</h1>
      <p class="subtitle">Your remote desktop session has been terminated and the container is shutting down.</p>
      <a href="{{ url_for('index') }}" class="btn">Log In Again</a>
    </div>
  </body>
</html>
"""

@app.route('/shutdown')
def shutdown():
    if 'user' not in session:
        return redirect(url_for('index'))
        
    user = session.get('user')
    display = session.get('display')
    
    # Clean up display/VNC server for the user if it exists
    if display is not None:
        try:
            kill_cmd = ['su', '-', user, '-c', f"vncserver -kill :{display}"]
            subprocess.run(kill_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except Exception as e:
            print(f"Error killing VNC on shutdown: {e}")
            
    # Clear the session
    session.clear()
    
    # Stop the container by killing PID 1
    def kill_container():
        time.sleep(1.0)
        os.kill(1, 15)  # SIGTERM to PID 1
        time.sleep(2.0)
        os.kill(1, 9)   # SIGKILL to PID 1 if SIGTERM didn't do it
        
    import threading
    threading.Thread(target=kill_container).start()
    
    return render_template_string(SHUTDOWN_PAGE)

def check_ldap_login(username, password):
    # Strip any domain/email suffix if present
    raw_user = username.split('@')[0]
    
    try:
        # Load TLS certificates for secure Google LDAP connection
        tls_config = Tls(
            local_private_key_file='/etc/kasm/auth/google.key',
            local_certificate_file='/etc/kasm/auth/google.crt',
            validate=ssl.CERT_NONE,
            version=ssl.PROTOCOL_TLS
        )
        
        # Connect to Google Secure LDAP server
        server = Server('ldap.google.com', port=636, use_ssl=True, tls=tls_config)
        
        # 1. Bind with SASL EXTERNAL using client certificates to perform user DN lookup
        admin_conn = Connection(server, authentication=ldap3.SASL, sasl_mechanism=ldap3.EXTERNAL)
        if not admin_conn.bind():
            print("Failed to perform SASL EXTERNAL admin bind")
            return False, None
            
        # Search for the user to get their exact DN
        admin_conn.search(
            search_base='dc=persimmons,dc=ai',
            search_filter=f'(uid={raw_user})',
            search_scope=ldap3.SUBTREE
        )
        
        if not admin_conn.entries:
            print(f"User '{raw_user}' not found in LDAP search")
            admin_conn.unbind()
            return False, None
            
        user_dn = admin_conn.entries[0].entry_dn
        admin_conn.unbind()
        
        # 2. Bind with SIMPLE authentication using the retrieved user DN and the user's password
        user_conn = Connection(server, user=user_dn, password=password, authentication=ldap3.SIMPLE)
        bind_success = user_conn.bind()
        user_conn.unbind()
        
        if bind_success:
            return True, raw_user
        else:
            print(f"LDAP password authentication failed for user DN: {user_dn}")
            return False, None
            
    except Exception as e:
        print(f"LDAP authentication error: {e}")
        return False, None

def chown_recursive(path, uid, gid):
    try:
        subprocess.run(['chown', '-R', f"{uid}:{gid}", path], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception as e:
        print(f"Error recursively chowning {path}: {e}")

def wait_for_port(port, timeout=5.0):
    import socket, time
    start_time = time.time()
    while time.time() - start_time < timeout:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(0.5)
        res = s.connect_ex(('127.0.0.1', port))
        s.close()
        if res == 0:
            return True
        time.sleep(0.1)
    return False

def find_user_display(username):
    try:
        cmd = ['su', '-', username, '-c', 'vncserver -list']
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
        for line in result.stdout.splitlines():
            parts = line.split()
            if len(parts) >= 2 and parts[0].startswith(':'):
                try:
                    display_num = int(parts[0][1:])
                    import socket
                    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                    s.settimeout(0.5)
                    res = s.connect_ex(('127.0.0.1', 5900 + display_num))
                    s.close()
                    if res == 0:
                        return display_num
                except ValueError:
                    continue
    except Exception as e:
        print(f"Error checking active VNC displays: {e}")
    return None

def ensure_user_home(username):
    import shutil
    try:
        pw = pwd.getpwnam(username)
        uid = pw.pw_uid
        gid = pw.pw_gid
    except KeyError:
        raise Exception(f"User '{username}' does not exist in the system (SSSD lookup failed)")
        
    # Path in the persistent work volume
    user_work_dir = f"/work/kasm_home/{username}"
    os.makedirs(user_work_dir, exist_ok=True)
    
    # If the user home is empty (or does not contain standard configs), copy skeleton files from /home/kasm_user
    # but skip active dynamic files like .Xauthority and .ICEauthority from copy
    if not os.path.exists(os.path.join(user_work_dir, '.config')):
        print(f"Populating home directory from skeleton/kasm_user for {username}...")
        for item in os.listdir('/home/kasm_user'):
            if item in ['.Xauthority', '.ICEauthority', '.vnc']:
                continue
            s = os.path.join('/home/kasm_user', item)
            d = os.path.join(user_work_dir, item)
            try:
                if os.path.isdir(s):
                    if not os.path.exists(d):
                        shutil.copytree(s, d, symlinks=True)
                else:
                    if not os.path.exists(d):
                        shutil.copy2(s, d)
            except Exception as e:
                print(f"Error copying skeleton item {item}: {e}")

    # Force desktop compositing to be disabled in the XFCE settings
    xfconf_dir = os.path.join(user_work_dir, '.config', 'xfce4', 'xfconf', 'xfce-perchannel-xml')
    os.makedirs(xfconf_dir, exist_ok=True)
    xfwm4_xml_path = os.path.join(xfconf_dir, 'xfwm4.xml')
    xfwm4_xml_content = """<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfwm4" version="1.0">
  <property name="general" type="empty">
    <property name="use_compositing" type="bool" value="false"/>
  </property>
</channel>
"""
    with open(xfwm4_xml_path, 'w') as f:
        f.write(xfwm4_xml_content)

    # Ensure proper ownership of the persistent home directory recursively
    chown_recursive(user_work_dir, uid, gid)
    
    # Symlink /home/<username> -> /work/kasm_home/<username>
    user_home = f"/home/{username}"
    is_correct_symlink = False
    if os.path.islink(user_home):
        try:
            if os.readlink(user_home) == user_work_dir:
                is_correct_symlink = True
        except Exception:
            pass
            
    if not is_correct_symlink:
        print(f"Correcting home directory symlink for {username}...")
        try:
            if os.path.islink(user_home) or os.path.exists(user_home):
                if os.path.isdir(user_home) and not os.path.islink(user_home):
                    shutil.rmtree(user_home)
                else:
                    os.remove(user_home)
            os.symlink(user_work_dir, user_home)
        except Exception as e:
            print(f"Error establishing home symlink: {e}")
        
    # Ensure .vnc directory and xstartup script exist for this user
    vnc_dir = os.path.join(user_work_dir, '.vnc')
    os.makedirs(vnc_dir, exist_ok=True)
    xstartup_path = os.path.join(vnc_dir, 'xstartup')
    
    xstartup_content = """#!/bin/sh
xrdb $HOME/.Xresources
vncconfig -nowin &

# Start DBus Session Bus
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval $(dbus-launch --sh-syntax)
    export DBUS_SESSION_BUS_ADDRESS
fi

# Start GNOME Keyring Daemon
if [ -z "$GNOME_KEYRING_CONTROL" ]; then
    eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
    export GNOME_KEYRING_CONTROL
    export SSH_AUTH_SOCK
fi

xset s off
xset s noblank
xset -dpms
startxfce4 &
"""
    with open(xstartup_path, 'w') as f:
        f.write(xstartup_content)
        
    # Make xstartup executable and set ownership
    os.chmod(xstartup_path, 0o755)
    
    # Recursively chown the .vnc directory to user:group
    chown_recursive(vnc_dir, uid, gid)
    
    # Ensure XFCE desktop background config points to our custom wallpaper
    xfconf_dir = os.path.join(user_work_dir, '.config', 'xfce4', 'xfconf', 'xfce-perchannel-xml')
    os.makedirs(xfconf_dir, exist_ok=True)
    desktop_xml_path = os.path.join(xfconf_dir, 'xfce4-desktop.xml')
    desktop_xml_content = """<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfce4-desktop" version="1.0">
  <property name="backdrop" type="empty">
    <property name="screen0" type="empty">
      <property name="monitorVNC-0" type="empty">
        <property name="workspace0" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/persimmons.png"/>
        </property>
        <property name="workspace1" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/persimmons.png"/>
        </property>
        <property name="workspace2" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/persimmons.png"/>
        </property>
        <property name="workspace3" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/persimmons.png"/>
        </property>
      </property>
      <property name="monitor0" type="empty">
        <property name="workspace0" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/persimmons.png"/>
        </property>
      </property>
      <property name="monitorDEFAULT" type="empty">
        <property name="workspace0" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/persimmons.png"/>
        </property>
      </property>
    </property>
  </property>
</channel>
"""
    with open(desktop_xml_path, 'w') as f:
        f.write(desktop_xml_content)
    chown_recursive(os.path.join(user_work_dir, '.config'), uid, gid)
    
    return uid, gid

@app.route('/login', methods=['POST'])
def login():
    username = request.form.get('username')
    password = request.form.get('password')
    
    if not username or not password:
        return render_template_string(LOGIN_PAGE, error="Username and password are required")
        
    success, raw_user = check_ldap_login(username, password)
    if not success:
        return render_template_string(LOGIN_PAGE, error="Invalid credentials or authentication failed")
        
    # Store user in session
    session['user'] = raw_user
    
    # Check if this user already has an active VNC display running
    display = find_user_display(raw_user)
    if display is not None:
        print(f"Found existing active VNC display :{display} for user {raw_user}. Reusing it.")
        session['display'] = display
        # Rewrite token file just in case it was deleted
        token_dir = '/tmp/tokens'
        os.makedirs(token_dir, exist_ok=True)
        token_file = os.path.join(token_dir, str(display))
        with open(token_file, 'w') as f:
            f.write(f"{display}: localhost:{5900 + display}\n")
    else:
        try:
            # Allocate display
            display = allocate_display(raw_user)
            session['display'] = display
            # Launch VNC for the LDAP user
            launch_user_vnc(raw_user, display)
        except Exception as e:
            print(f"Error launching VNC for {raw_user}: {e}")
            return render_template_string(LOGIN_PAGE, error=f"Failed to start desktop environment: {e}")
        
    return redirect(url_for('novnc', cb=int(time.time())))

def get_saml_client(host_url):
    import saml2
    from saml2.config import SPConfig
    from saml2.client import Saml2Client
    
    # IDP Cert
    idp_cert_path = '/etc/kasm/auth/google_idp.crt'
    if os.path.exists(idp_cert_path):
        with open(idp_cert_path) as f:
            idp_cert = f.read()
    else:
        idp_cert = ""
        
    acs_url = saml_cfg.get('acs_url') or f"{host_url}/saml/acs"
    config_dict = {
        'entityid': saml_cfg.get('entity_id', 'kasm-sp'),
        'service': {
            'sp': {
                'endpoints': {
                    'assertion_consumer_service': [
                        (acs_url, saml2.BINDING_HTTP_POST)
                    ],
                },
                'allow_unsolicited': True,
                'authn_requests_signed': False,
                'want_assertions_signed': True,
                'want_response_signed': False,
            },
        },
        'key_file': '/etc/kasm/auth/google.key',
        'cert_file': '/etc/kasm/auth/google.crt',
        'metadata': {
            'local': ['/etc/kasm/auth/google_idp_metadata.xml']
        }
    }
    sp_config = SPConfig()
    sp_config.load(config_dict)
    return Saml2Client(sp_config)

@app.route('/saml/login')
def saml_login():
    proto = request.headers.get('X-Forwarded-Proto', 'https')
    host_url = f"{proto}://{request.host}"
    
    client = get_saml_client(host_url)
    session_id, info = client.prepare_for_authenticate()
    
    redirect_url = None
    for key, val in info.get('headers', []):
        if key.lower() == 'location':
            redirect_url = val
            break
            
    if not redirect_url:
        return "Failed to generate SAML redirect URL", 500
        
    return redirect(redirect_url)

@app.route('/saml/acs', methods=['POST'])
def saml_acs():
    saml_response = request.form.get('SAMLResponse')
    if not saml_response:
        return "SAMLResponse is missing", 400
        
    proto = request.headers.get('X-Forwarded-Proto', 'https')
    host_url = f"{proto}://{request.host}"
    
    try:
        client = get_saml_client(host_url)
        authn_response = client.parse_authn_request_response(
            saml_response,
            saml2.BINDING_HTTP_POST
        )
        
        name_id = authn_response.name_id
        email = name_id.text if name_id else None
        
        if not email:
            identity = authn_response.get_identity()
            attr_name = saml_cfg.get('assertion_attribute', 'mail')
            if identity and attr_name in identity:
                email = identity[attr_name][0]
                
        if not email:
            return redirect(url_for('index', error="Failed to extract username or email from SAML assertion"))
            
        raw_user = email.split('@')[0]
        
        try:
            ensure_user_home(raw_user)
        except Exception as e:
            return redirect(url_for('index', error=f"Authenticated as {raw_user}, but local system lookup failed: {e}"))
            
        session['user'] = raw_user
        
        display = find_user_display(raw_user)
        if display is not None:
            session['display'] = display
            token_dir = '/tmp/tokens'
            os.makedirs(token_dir, exist_ok=True)
            token_file = os.path.join(token_dir, str(display))
            with open(token_file, 'w') as f:
                f.write(f"{display}: localhost:{5900 + display}\n")
        else:
            display = allocate_display(raw_user)
            session['display'] = display
            launch_user_vnc(raw_user, display)
            
        return redirect(url_for('novnc', cb=int(time.time())))
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        return redirect(url_for('index', error=f"SAML login failed: {e}"))


def is_port_in_use(port):
    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(0.1)
    res = s.connect_ex(('127.0.0.1', port))
    s.close()
    return res == 0

def allocate_display(user):
    lock_path = '/tmp/display_alloc.lock'
    # Simple lock using flock
    import fcntl, time
    with open(lock_path, 'w') as lock_file:
        fcntl.flock(lock_file, fcntl.LOCK_EX)
        display = 10
        while True:
            port = 5900 + display
            x_port = 6000 + display
            if not is_port_in_use(port) and not is_port_in_use(x_port):
                if not os.path.exists(f"/tmp/.X{display}-lock") and not os.path.exists(f"/tmp/.X11-unix/X{display}"):
                    break
            display += 1
            if display > 100:
                fcntl.flock(lock_file, fcntl.LOCK_UN)
                raise Exception("No free VNC display slot available")
        fcntl.flock(lock_file, fcntl.LOCK_UN)
    return display

def launch_user_vnc(user, display):
    # Setup home directory and get UID/GID
    uid, gid = ensure_user_home(user)
    
    # Write token file for websockify to enable routing
    token_dir = '/tmp/tokens'
    os.makedirs(token_dir, exist_ok=True)
    token_file = os.path.join(token_dir, str(display))
    with open(token_file, 'w') as f:
        f.write(f"{display}: localhost:{5900 + display}\n")
        
    # Clean any stale VNC/X locks and unix sockets for this display
    lock_file = f"/tmp/.X{display}-lock"
    if os.path.exists(lock_file):
        try:
            os.remove(lock_file)
        except Exception:
            pass
    socket_file = f"/tmp/.X11-unix/X{display}"
    if os.path.exists(socket_file):
        try:
            os.remove(socket_file)
        except Exception:
            pass
            
    # Kill any stale session for this display first as the user
    kill_cmd = ['su', '-', user, '-c', f"vncserver -kill :{display}"]
    subprocess.run(kill_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    # Start a VNC server bound to the same display, no password, localhost only
    vnc_cmd = ['su', '-', user, '-c', f"vncserver :{display} -geometry 1280x720 -depth 24 -SecurityTypes None -PasswordFile /dev/null -localhost no -listen tcp"]
    subprocess.Popen(vnc_cmd)
    
    # Wait for the VNC server to start listening before returning
    wait_for_port(5900 + display)

@app.route('/novnc')
def novnc():
    if 'user' not in session:
        return redirect(url_for('index'))
    display = session.get('display')
    # noVNC is served from /opt/novnc/vnc_lite.html inside the container – expose via Flask static route.
    # We proxy WebSocket connection over the same external port mapped to Nginx (port 8000 by default)
    host_parts = request.host.split(':')
    client_host = host_parts[0]
    client_port = host_parts[1] if len(host_parts) > 1 else '8000'
    response = redirect(f"/novnc/vnc_lite.html?host={client_host}&port={client_port}&path=websockify%3Ftoken%3D{display}&autoconnect=true&resize=remote&display=:{display}")
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response

# Serve the noVNC static files
@app.route('/novnc/<path:filename>')
def novnc_static(filename):
    if 'user' not in session:
        return redirect(url_for('index'))
    return send_from_directory('/opt/novnc', filename)

if __name__ == '__main__':
    # Bind to 127.0.0.1:5000 as plain HTTP behind Nginx reverse proxy
    app.run(host='127.0.0.1', port=5000)
